<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxdZqE8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxdZqE8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxdZqE8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxdZqE8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxdZqE8\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxdZqE8',
    'container.build_id' => '8cebd15f',
    'container.build_time' => 1631033922,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxdZqE8');
